### ISSUE TITLE
Missing a LICENSE

### ISSUE THREAD

**Issue by logankoester** [blazer82/meteor-casperjs#11]
Please add a license, even if you are no longer interested in maintaining this project, so that others may legally continue to use (and fork) it.

If you are unfamiliar with software licensing, the [MIT License](https://en.wikipedia.org/wiki/MIT_License) is a common choice with permissive terms.

**Comment by blazer82** [comment]
Good point! Thank you! I added the MIT license.

**Comment by logankoester** [comment]
Thank you! :grin:
